spring:
  datasource:
    url: jdbc:h2:file:./target/h2db/db/task;AUTO_SERVER=TRUE;DB_CLOSE_DELAY=-1
    username: berny
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true